** credits to wikitubia for fetch.yml code **
** modified by RedHandsome128 **

name: Fetch from source
on:
  schedule:
    - cron:  0 0 * * 2,5
  workflow_dispatch:

jobs:
  Get-Source:
    env:
      FETCH_URL: 'https://prison-life.fandom.com/wiki/MediaWiki:Fandomdesktop.css?action=raw'
    name: Fetch and commit source
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '[INFO] Setting Git up...'
      - run: git config --global user.name 'Actions'; git config --global user.email 'actions@github.com'
      - run: echo "[INFO] Scheduled run each 0:00 UTC every Tuesday and Friday"
      - run: echo "[INFO] Fetching from site..."
      - run: echo "[INFO] $GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE"
      - run: wget -P /home/runner/work/Fandomdesktop.css -O Fandomdesktop.css '${{env.FETCH_URL}}'
      - run: git add Fandomdesktop.css
      - run: git commit -m 'Fetch latest revision from URL' && git push -u origin main || echo '[INFO] Source is the same as repository. Skipping push...'
      - run: echo '[EXIT] Job done!'; exit 0
